### ISSUE TITLE
script errors on load?

### ISSUE THREAD

**Issue by dazinator** [alexisvincent/systemjs-hmr#29]
Having put these two scripts on a page:

     <script src="~/lib/systemjs/system.js"></script>
     <script src="~/lib/systemjs-hmr/dist/systemjs-hmr.js"></script>

The systemjs-hmr.js script errors on load with:

![image](https://user-images.githubusercontent.com/3176632/49088239-bb640580-f250-11e8-8de3-c89eebc5a0da.png)

![image](https://user-images.githubusercontent.com/3176632/49088191-a1c2be00-f250-11e8-810e-8d8f3d705764.png)

This is using `systemjs-hmr@2.0.9` and `systemjs@2.1.1`

Am I doing something stupid?

**Comment by alexisvincent** [comment]
So the issue is that this library hasn't been updated to function with SystemJS >2.0.0. Largely because I'm primarily writing clojure(script) now and haven't had time to focus on this library.

So you're not doing anything stupid. 

I strongly expect with some structural work this could be updated to work, especially since v2 seems to have more exposed that would make HMR even easier. However, I don't currently have time to do the work myself.

If you would be up for having a look, I can provide some support.

**Comment by dazinator** [comment]
Ok, I am just trying to get to grips with the basics at present, in fact I am getting a very basic sample up and running. Not using any transpilation, just loading an AMD module into the browser, and then in the console I am calling System.reload('moduleId');

I have been testing with system 0.21 and I'll send a PR to make that work, as currently it doesn't (system 0.19 and 0.20 do work). I am testing with 0.21.5 because that is is the latest system release prior to the jump to 2.0 and it so it seems like it's a lot less effort to get this working first whilst I learn my way around :-)

**Comment by dazinator** [comment]
Im going to close this, Ill open a new issue to track support for systemjs 2.0 but I won't be working on that I suspect for a while, as I am happy for the time being on 0.21 ;-)
